### ISSUE TITLE
Bug: touchscreen does not work out of the box on `chilipie-kiosk`

### ISSUE THREAD

**Issue by m-roberts** [pi-top/pi-top-4-Touchscreen#15]
I am not sure why, but the device does not appear to be recognised when using [`chilipie-kiosk`](https://github.com/jareware/chilipie-kiosk).

It does not appear to even show up in `lsusb` or the compatible list of devices when `touchegg` is installed (which uses `libinput`).

Perhaps some sort of dependency is missing?

**Comment by m-roberts** [comment]
Seems as though this is something to do with [disabling automatic root filesystem expansion](https://github.com/jareware/chilipie-kiosk/blob/master/docs/image-setup.sh#L72), as this is [no longer an issue](https://github.com/m-roberts/chilipie-kiosk/commit/bd635381ddfa9e10745562e8cdfc6c69283624c9) in my fork.

**Comment by reinierdevl** [comment]
I'm having the same issue. My touchscreen works fine when I use a buster implementation, but can't get it to work on chilipie
